### ISSUE TITLE
hw-balancedparens-0.4.1.2 fails to build with ghc-9.4.3 in Stackage Nightly

### ISSUE THREAD

**Issue by juhp** [haskell-works/hw-balancedparens#166]
```
Building library for hw-balancedparens-0.4.1.2..
[19 of 55] Compiling HaskellWorks.Data.BalancedParens.Internal.ParensSeq

/var/stackage/work/unpack-dir/unpacked/hw-balancedparens-0.4.1.2-315cc4da305f32c316053f80848d34656379bd5d2a3d6dd0b8f88ce46f6685a9/sr
c/HaskellWorks/Data/BalancedParens/Internal/ParensSeq.hs:126:27: error:
    Ambiguous occurrence ‘size’
    It could refer to
       either the field ‘size’ of record ‘Measure’,
              defined at src/HaskellWorks/Data/BalancedParens/Internal/ParensSeq.hs:47:5
           or the field ‘size’ of record ‘Elem’,
              defined at src/HaskellWorks/Data/BalancedParens/Internal/ParensSeq.hs:41:5
    |
126 | atSizeBelowZero n m = n < size (m :: Measure)
    |                           ^^^^
```

**Comment by sheaf** [comment]
I have fixed this in #167.
